---
title: "SENG RATHANAK - Midterm - Data Science - Q3"
output: html_notebook
---

# Link to the post
https://www.phnompenhpost.com/national/mekong-levels-set-drop-during-power-grid-work


# import library
```{r}
library(tidytext)
library(sentimentr)
```


# read .txt file
```{r}
text_data <- "The water levels along the Mekong River in Thailand, Laos and Cambodia are set to drop due to decreased outflows at the Jinghong hydropower station in China's Yunnan province as China conducts maintenance on its power grid infrastructure from January 5 to 24.A statement from the inter-governmental Mekong River Commission (MRC) on January 6 announced that the maintenance would result in a reduced water flow of 1,000 cubic metres per second (m3/s) from January 5-24, citing information from China's Ministry of Water Resources.The flow rate will gradually return to normal from January 25, but the ministry did not specify river levels before the reduction or the volume to be restored, the statement said.The MRC observed that the outflow level at Jinghong began decreasing from 1,410m3/s on December 31 to 768m3/s on January 1, representing a nearly 50 per cent drop. The flow rate rose slightly to 786m3/s between January 1-4."
text_data
```

# perform tokenization and count the word
```{r}
# create a dataframe from the text file
dataframe <- data.frame(S.NO=1, Text=text_data)

tokenized_data <- dataframe %>% 
  # tokenization
  unnest_tokens(Info, Text) %>%
  # count the value
  count(Info, sort=TRUE)

# assign the most repeated value to "KIT"
tokenized_data[1, 1] = "KIT"

tokenized_data
```

# perform Sentiment analysis
```{r}
sentiment <- sentimentr::sentiment(text_data)
sentiment
```

# plot graph between "words count" and "words"
```{r}
# Perform on only first 40 rows of the records
tokenized_data[c(1:40), ] %>%
  ggplot(aes(n, Info)) +
  geom_col() +
  ggtitle("Text Mining using R") +
  xlab("Number of words") +
  ylab("List of words") +
  theme( 
    axis.title.x = element_text(size=10, face="bold", color="blue", hjust=0.5, margin=margin(t=20)),
    axis.title.y = element_text(size=10, face="bold", color="red", hjust=0.5, margin=margin(r=20)),
    title = element_text(size=25, face="bold", color="yellow", hjust=0.5, margin=margin(b=25))
  )
```
